---
- name: "lamp install"
  hosts: amazon
  become: true
  vars_files:
    - apache.vars
    - domain.vars
    - mariadb.vars
  vars:
    wordpress_url: "https://wordpress.org/wordpress-5.7.3.tar.gz"
  tasks:

    - name: "apache install"
      yum:
        name: httpd
        state: present

    - name: "enable php"
      shell: amazon-linux-extras install php7.4 -y

    - name: "httpd.conf generate"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/httpd/conf.d/{{ httpd_domain }}.conf"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "DocumentRoot"
      file:
        path: "/var/www/html/{{ httpd_domain }}"
        state: directory
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "sample tset pages"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ httpd_domain }}/"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"
      with_items:
        - test.php
        - test.html

    - name: "apache restart"
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "mariadb install"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present

    - name: "mariadb service"
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: "mariadb server reset root password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ sql_root_password }}"
        host_all: true

    - name: "Removing Anonymous Users"
      mysql_user:
        login_user: "root"
        login_password: "{{ sql_root_password }}"
        user: ""
        state: absent

    - name: "Removing test database"
      mysql_db:
        login_user: "root"
        login_password: "{{ sql_root_password }}"
        name: "test"
        state: absent

    - name: "Creating extra database"
      mysql_db:
        login_user: root
        login_password: "{{ sql_root_password }}"
        name: "{{ sql_extra_database }}"
        state: present

    - name: "Creating Extra user"
      mysql_user:
        login_user: root
        login_password: "{{ sql_root_password }}"
        user: "{{ sql_extra_user }}"
        password: "{{ sql_extra_user_password }}"
        state: present
        priv: '{{ sql_extra_database }}.*:ALL'

    - name: "download wordpress"
      get_url:
        url: "{{ wordpress_url }}"
        dest: "/tmp/wordpress.tar.gz"

    - name: "extract downloaded wordpress"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/tmp"
        remote_src: true

    - name: "Copying Contents"
      copy:
        src: "/tmp/wordpress/"
        dest: "/var/www/html/{{ httpd_domain }}"
        remote_src: true
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "Wordpress - Generating wp-config.php from template"
      template:
        src: wp-config.php.tmpl
        dest: "/var/www/html/{{ httpd_domain }}/wp-config.php"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "post -installation clean up"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/wordpress"
        - "/tmp/wordpress.tar.gz"

    - name: "post installtion -restart"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - httpd
        - mariadb